export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTO = 'FETCH_PHOTO';
export const SET_PHOTOS_CURRENT_PAGE = 'SET_PHOTOS_CURRENT_PAGE';
export const FETCH_ALBUM = 'FETCH_ALBUM';
export const FETCH_USER = 'FETCH_USER';
